In [2]:
import numpy as np

In [3]:
a = np.array([[10,15]])
b = np.array([[20,9]])
a+b

array([[30, 24]])

In [4]:
print(a)

[[10 15]]


In [5]:
a.T + b.T

array([[30],
       [24]])

In [6]:
#subtract 2 vectors
a-b

array([[-10,   6]])

In [7]:
(a-b).T

array([[-10],
       [  6]])

In [8]:
#scalar multioplication
a=2
u=np.array([[30,15]])
(a*u)

array([[60, 30]])

In [10]:
#dot product for 2 vectors
#for 2D vectors it is the equiv to matrix multiplication

u=np.array([10,20])
v=np.array([25,6])
print(10*25+20*6)
np.dot(u,v)

370


370

In [18]:
#matrix addition
a=np.array([[12,10],[4,6],[40,31],])
b=np.array([[2,8],[46,63],[50,10],])
print(a)
print(b)

[[12 10]
 [ 4  6]
 [40 31]]
[[ 2  8]
 [46 63]
 [50 10]]


In [15]:
print(a, end= " = a\n\n")

[[12 10]
 [ 4  6]
 [40 31]] = a



In [16]:
a+b

array([[14, 18],
       [50, 69],
       [90, 41]])

In [17]:
a-b

array([[ 10,   2],
       [-42, -57],
       [-10,  21]])

In [19]:
#matrix and vector multiplication
a=[[5,10],[15,20]]
b=[10,12]
np.dot(a,b)

array([170, 390])

In [20]:
#matrix to matrix multiplication
a=[[5,10],[15,20],[25,30]]
b=[[3,6],[9,5]]
np.dot(a,b)

array([[105,  80],
       [225, 190],
       [345, 300]])

In [22]:
#transpose matrix
a=np.array([[5,10],[15,20],[25,30]])
print(a,end = " = a\n\n")
print(a.T,end = " = aT")

[[ 5 10]
 [15 20]
 [25 30]] = a

[[ 5 15 25]
 [10 20 30]] = aT

In [23]:
#create identity matrix

I1=np.eye(2)
I2=np.eye(3)
print(I1, end = " = I1\n\n")
print(I2, end = " = I2\n\n")

[[1. 0.]
 [0. 1.]] = I1

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] = I2



In [29]:
#inverse a matrix
#give a square matrix a, return matrix a inverse satisfying dot (a,ainv) = dot (ainv,a) = eye(a.shape[0])
a = np.array([
    [2, 1, 0],
    [0, 1, 0],
    [1, 2, 1],
])
print (a, end = " = a\n\n")
print(np.linalg.inv(a), end = " = l a l ")

[[2 1 0]
 [0 1 0]
 [1 2 1]] = a

[[ 0.5 -0.5  0. ]
 [ 0.   1.   0. ]
 [-0.5 -1.5  1. ]] = l a l 